// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQy_e-vfilZ12HUcsXx8DKk3UL9GrfHcc',
    appId: '1:690102906466:web:f200d46bfc5d2632c1ab3b',
    messagingSenderId: '690102906466',
    projectId: 'test-680fd',
    authDomain: 'test-680fd.firebaseapp.com',
    storageBucket: 'test-680fd.firebasestorage.app',
    measurementId: 'G-ZF5YCJJYW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD204h1jwaJhAcymV5_1evGAFn1VMs9qX4',
    appId: '1:690102906466:android:9092cc0c1aa4a29fc1ab3b',
    messagingSenderId: '690102906466',
    projectId: 'test-680fd',
    storageBucket: 'test-680fd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTQmGn7HmUxtl82h247dAkIipfPf0nkyA',
    appId: '1:690102906466:ios:da5f606445f05816c1ab3b',
    messagingSenderId: '690102906466',
    projectId: 'test-680fd',
    storageBucket: 'test-680fd.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTQmGn7HmUxtl82h247dAkIipfPf0nkyA',
    appId: '1:690102906466:ios:da5f606445f05816c1ab3b',
    messagingSenderId: '690102906466',
    projectId: 'test-680fd',
    storageBucket: 'test-680fd.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQy_e-vfilZ12HUcsXx8DKk3UL9GrfHcc',
    appId: '1:690102906466:web:660121ee13f041a8c1ab3b',
    messagingSenderId: '690102906466',
    projectId: 'test-680fd',
    authDomain: 'test-680fd.firebaseapp.com',
    storageBucket: 'test-680fd.firebasestorage.app',
    measurementId: 'G-1BQMRDCHGH',
  );
}
